FROM node:20-alpine

WORKDIR /app

COPY package.json ./client/package.json
COPY package-lock.json ./client/package-lock.json

RUN npm install --prefix ./client

COPY . /app

WORKDIR /app/client

RUN npm run build

FROM nginx:stable-alpine

COPY --from=0 /app/client/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

