version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interactive-letter-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/service_account.json:/app/service_account.json:ro
      - ./server/data:/app/data
      - ./server/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=5000
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # Proxy configuration for backend
      - HTTP_PROXY=socks5://127.0.0.1:10808
      - HTTPS_PROXY=socks5://127.0.0.1:10808
      - NO_PROXY=localhost,127.0.0.1,backend,frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: interactive-letter-frontend
    ports:
      - "3000:80" # Map port 3000 to 80 for easier access
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


