FROM node:20-alpine

WORKDIR /app

COPY package.json ./server/package.json
COPY package-lock.json ./server/package-lock.json

RUN npm install --prefix ./server

COPY . /app

WORKDIR /app/server

EXPOSE 5000

CMD ["npm", "start"]

